# Generated by Django 3.2.16 on 2024-04-19 09:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_follow_user_prevent_self_follow'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='follow',
            name='user_prevent_self_follow',
        ),
    ]
