# Generated by Django 3.2.16 on 2024-04-19 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_remove_follow_user_prevent_self_follow'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='follow',
            name='user_name_follow',
        ),
    ]
